language: php

php:
  - 7.2
  - 7.3
  - 7.4

os:
  - linux

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev
  - cd tests

script:
  - ../vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)